format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[cmd_duration]
format = "[$duration]($style) "

[python]
format = "[$virtualenv]($style) "
