import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Transparent"
padding = { x = 6, y = 25 }
dynamic_padding = true

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "SemiBold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
size = 16.0

[selection]
save_to_clipboard = true
